<?php
/**
 * @file
 * This file implements various hooks and functions.
 */

 /**
  * Implements hook_help().
  */
  function unical_help($path, $arg) {
   switch ($path) {
     case 'admin/help#unical':

       $filepath = dirname(__FILE__) . '/README.md';
       if (file_exists($filepath)) {
         $readme = file_get_contents($filepath);
       }
       else {
         $filepath = dirname(__FILE__) . '/README.txt';
         if (file_exists($filepath)) {
           $readme = file_get_contents($filepath);
         }
       }
       if (!isset($readme)) {
         return NULL;
       }
       if (module_exists('markdown')) {
         $filters = module_invoke('markdown', 'filter_info');
         $info = $filters['filter_markdown'];

         if (function_exists($info['process callback'])) {
           $output = $info['process callback']($readme, NULL);
         }
         else {
           $output = '<pre>' . $readme . '</pre>';
         }
       }
       else {
         $output = '<pre>' . $readme . '</pre>';
       }

       return $output;
   }
 }

 /**
  * Implements hook_ctools_plugin_directory().
  */
  function unical_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
  }

  /**
   * Implements hook_theme().
   */
  function unical_theme($existing, $type, $theme, $path) {
    return array(
      'node__site' => array(
        'render element' => 'content',
        'base hook' => 'node',
        'template' => 'node--site',
        'path' => drupal_get_path('module', 'unical') . '/templates/node',
      ),
    );
  }

  /**
   * Implements hook_menu().
   */
  function unical_menu() {
    $items = array();

    $items['node/%node/calendar-site-settings-embed'] = array(
      'title' => 'Embed/Install Instructions',
      'page callback' => '_unical_client',
      'page arguments' => array(1),
      'access callback' => '_unical_check_tab_permission',
      'access arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
    );

    return $items;
  }

  /**
   * Function for the hook_menu() above. Create a tab to show embed info/etc.
   */
  function _unical_client() {
    // Define site URL.
    $url = $GLOBALS['base_url'];
    // Get nid from url, as we dont have access to $node.
    $node_path = explode('/', $_SERVER["REQUEST_URI"]);
    $nid = $node_path[2];

    $embed_code = htmlspecialchars('<link rel="stylesheet" href="' . $url . '/sites/all/modules/unical/assets/css/styles.css"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"><script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <div ng-app="calendar" class="unical-calendar"><h1>Calendar of Events</h1><div ng-view></div></div><script>var site_url = "' . $url . '/api/";
  var site_id =' . $nid . ';</script><script src="http://dev.calendar.howard.edu/sites/all/modules/unical/app/build/unical.js"></script>');

    $embed_text = "
  <h1>Embed/Install Instructions</h1>
  <p>In addition to the individual site calendars being available on this site, they are also available for embedding either through the unical_client module for drupal sites, or by simply adding the code snippet at the bottom of the page.</p>
  <h3>Drupal Module:</h3>
  <p>Add the following to the modules settings page:</p>
    <ul>
      <li><strong>Site URL</strong>: " . $url . "/</li>
      <li><strong>Site ID</strong>: " . $nid . "</li>
    </ul>
  <h3>Manual Embed Code:</h3>
  <p>The following can be embedded on any relevant HTML page, regardless of the CMS/etc. This can be modified and separated into more optimized areas of the site (head/footer/etc) if desired.</p>
  <p>The main components needed are:</p>
    <ul>
      <li>Styles.css for the calendar.</li>
      <li>Font awesome css (4.4)(eliminate if site is already using).</li>
      <li>jquery > 1.10.2 (eliminate if site is already using).</li>
      <li>Divs that will render the app.</li>
      <li>JS variables to tell the calendar which site to use.</li>
      <li>The main app JS.</li>
    </ul>
    <code> " . $embed_code . "</code>";

    return $embed_text;

  }

  /**
   * Check whether to display "Settings/Embed" tab.
   */
  function _unical_check_tab_permission($node) {
    global $user;
    if ($node->type == 'site' && in_array('administrator', $user->roles)) {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }

/**
 * Expires dates in repeating events, so sort works on next date in series
 *
 */
function _unical_expire_repeating_events() {
  
  $result = db_query(
    'UPDATE {field_data_field_date} SET deleted = :deleted WHERE field_date_value < :datenow AND field_date_rrule != :rrule', array(
      ':datenow' => date('Y-m-d H:i:s'),
      ':rrule' => 'null',
      ':deleted' => 1
    )
  );
  
  watchdog('unical', $result->rowCount() . ' repeating event dates were set to expired', array(), WATCHDOG_NOTICE);
  
}

/**
 * Cron hook
 *
 */
function unical_cron() {
  
  //Don't implement yet
  //_unical_expire_repeating_events();
  
}
